// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPIr0Bq_5ieLZrxkPnz9ZlfaxJsTMQ_s',
    appId: '1:569490492116:web:42902dbb84c958eb288941',
    messagingSenderId: '569490492116',
    projectId: 'packaging-report',
    authDomain: 'packaging-report.firebaseapp.com',
    storageBucket: 'packaging-report.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZrvYhXGlT-DDCLXk6YIVY0YurSAAgYbI',
    appId: '1:569490492116:android:898a42cf9b5853af288941',
    messagingSenderId: '569490492116',
    projectId: 'packaging-report',
    storageBucket: 'packaging-report.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7h8RHNKUc0NEcs1UMtA5i5w9aeIneiFI',
    appId: '1:569490492116:ios:19f0ae25ec867fa1288941',
    messagingSenderId: '569490492116',
    projectId: 'packaging-report',
    storageBucket: 'packaging-report.firebasestorage.app',
    iosBundleId: 'com.example.tslPackaging',
  );
}
